/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as ManufacturingRouteImport } from './routes/manufacturing'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HrRouteImport } from './routes/hr'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsIndexRouteImport } from './routes/assets.index'
import { Route as AssetsReportsRouteImport } from './routes/assets.reports'
import { Route as AssetsRegisterRouteImport } from './routes/assets.register'
import { Route as AssetsMastersRouteImport } from './routes/assets.masters'
import { Route as AssetsLifecycleRouteImport } from './routes/assets.lifecycle'
import { Route as AssetsRegisterIdRouteImport } from './routes/assets.register.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturingRoute = ManufacturingRouteImport.update({
  id: '/manufacturing',
  path: '/manufacturing',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssetsRoute,
} as any)
const AssetsReportsRoute = AssetsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AssetsRoute,
} as any)
const AssetsRegisterRoute = AssetsRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AssetsRoute,
} as any)
const AssetsMastersRoute = AssetsMastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => AssetsRoute,
} as any)
const AssetsLifecycleRoute = AssetsLifecycleRouteImport.update({
  id: '/lifecycle',
  path: '/lifecycle',
  getParentRoute: () => AssetsRoute,
} as any)
const AssetsRegisterIdRoute = AssetsRegisterIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AssetsRegisterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/assets': typeof AssetsRouteWithChildren
  '/crm': typeof CrmRoute
  '/finance': typeof FinanceRoute
  '/hr': typeof HrRoute
  '/inventory': typeof InventoryRoute
  '/manufacturing': typeof ManufacturingRoute
  '/payroll': typeof PayrollRoute
  '/procurement': typeof ProcurementRoute
  '/projects': typeof ProjectsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/assets/lifecycle': typeof AssetsLifecycleRoute
  '/assets/masters': typeof AssetsMastersRoute
  '/assets/register': typeof AssetsRegisterRouteWithChildren
  '/assets/reports': typeof AssetsReportsRoute
  '/assets/': typeof AssetsIndexRoute
  '/assets/register/$id': typeof AssetsRegisterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/crm': typeof CrmRoute
  '/finance': typeof FinanceRoute
  '/hr': typeof HrRoute
  '/inventory': typeof InventoryRoute
  '/manufacturing': typeof ManufacturingRoute
  '/payroll': typeof PayrollRoute
  '/procurement': typeof ProcurementRoute
  '/projects': typeof ProjectsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/assets/lifecycle': typeof AssetsLifecycleRoute
  '/assets/masters': typeof AssetsMastersRoute
  '/assets/register': typeof AssetsRegisterRouteWithChildren
  '/assets/reports': typeof AssetsReportsRoute
  '/assets': typeof AssetsIndexRoute
  '/assets/register/$id': typeof AssetsRegisterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administration': typeof AdministrationRoute
  '/assets': typeof AssetsRouteWithChildren
  '/crm': typeof CrmRoute
  '/finance': typeof FinanceRoute
  '/hr': typeof HrRoute
  '/inventory': typeof InventoryRoute
  '/manufacturing': typeof ManufacturingRoute
  '/payroll': typeof PayrollRoute
  '/procurement': typeof ProcurementRoute
  '/projects': typeof ProjectsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/assets/lifecycle': typeof AssetsLifecycleRoute
  '/assets/masters': typeof AssetsMastersRoute
  '/assets/register': typeof AssetsRegisterRouteWithChildren
  '/assets/reports': typeof AssetsReportsRoute
  '/assets/': typeof AssetsIndexRoute
  '/assets/register/$id': typeof AssetsRegisterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administration'
    | '/assets'
    | '/crm'
    | '/finance'
    | '/hr'
    | '/inventory'
    | '/manufacturing'
    | '/payroll'
    | '/procurement'
    | '/projects'
    | '/sales'
    | '/settings'
    | '/assets/lifecycle'
    | '/assets/masters'
    | '/assets/register'
    | '/assets/reports'
    | '/assets/'
    | '/assets/register/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administration'
    | '/crm'
    | '/finance'
    | '/hr'
    | '/inventory'
    | '/manufacturing'
    | '/payroll'
    | '/procurement'
    | '/projects'
    | '/sales'
    | '/settings'
    | '/assets/lifecycle'
    | '/assets/masters'
    | '/assets/register'
    | '/assets/reports'
    | '/assets'
    | '/assets/register/$id'
  id:
    | '__root__'
    | '/'
    | '/administration'
    | '/assets'
    | '/crm'
    | '/finance'
    | '/hr'
    | '/inventory'
    | '/manufacturing'
    | '/payroll'
    | '/procurement'
    | '/projects'
    | '/sales'
    | '/settings'
    | '/assets/lifecycle'
    | '/assets/masters'
    | '/assets/register'
    | '/assets/reports'
    | '/assets/'
    | '/assets/register/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministrationRoute: typeof AdministrationRoute
  AssetsRoute: typeof AssetsRouteWithChildren
  CrmRoute: typeof CrmRoute
  FinanceRoute: typeof FinanceRoute
  HrRoute: typeof HrRoute
  InventoryRoute: typeof InventoryRoute
  ManufacturingRoute: typeof ManufacturingRoute
  PayrollRoute: typeof PayrollRoute
  ProcurementRoute: typeof ProcurementRoute
  ProjectsRoute: typeof ProjectsRoute
  SalesRoute: typeof SalesRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturing': {
      id: '/manufacturing'
      path: '/manufacturing'
      fullPath: '/manufacturing'
      preLoaderRoute: typeof ManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/'
      fullPath: '/assets/'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/assets/reports': {
      id: '/assets/reports'
      path: '/reports'
      fullPath: '/assets/reports'
      preLoaderRoute: typeof AssetsReportsRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/assets/register': {
      id: '/assets/register'
      path: '/register'
      fullPath: '/assets/register'
      preLoaderRoute: typeof AssetsRegisterRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/assets/masters': {
      id: '/assets/masters'
      path: '/masters'
      fullPath: '/assets/masters'
      preLoaderRoute: typeof AssetsMastersRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/assets/lifecycle': {
      id: '/assets/lifecycle'
      path: '/lifecycle'
      fullPath: '/assets/lifecycle'
      preLoaderRoute: typeof AssetsLifecycleRouteImport
      parentRoute: typeof AssetsRoute
    }
    '/assets/register/$id': {
      id: '/assets/register/$id'
      path: '/$id'
      fullPath: '/assets/register/$id'
      preLoaderRoute: typeof AssetsRegisterIdRouteImport
      parentRoute: typeof AssetsRegisterRoute
    }
  }
}

interface AssetsRegisterRouteChildren {
  AssetsRegisterIdRoute: typeof AssetsRegisterIdRoute
}

const AssetsRegisterRouteChildren: AssetsRegisterRouteChildren = {
  AssetsRegisterIdRoute: AssetsRegisterIdRoute,
}

const AssetsRegisterRouteWithChildren = AssetsRegisterRoute._addFileChildren(
  AssetsRegisterRouteChildren,
)

interface AssetsRouteChildren {
  AssetsLifecycleRoute: typeof AssetsLifecycleRoute
  AssetsMastersRoute: typeof AssetsMastersRoute
  AssetsRegisterRoute: typeof AssetsRegisterRouteWithChildren
  AssetsReportsRoute: typeof AssetsReportsRoute
  AssetsIndexRoute: typeof AssetsIndexRoute
}

const AssetsRouteChildren: AssetsRouteChildren = {
  AssetsLifecycleRoute: AssetsLifecycleRoute,
  AssetsMastersRoute: AssetsMastersRoute,
  AssetsRegisterRoute: AssetsRegisterRouteWithChildren,
  AssetsReportsRoute: AssetsReportsRoute,
  AssetsIndexRoute: AssetsIndexRoute,
}

const AssetsRouteWithChildren =
  AssetsRoute._addFileChildren(AssetsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministrationRoute: AdministrationRoute,
  AssetsRoute: AssetsRouteWithChildren,
  CrmRoute: CrmRoute,
  FinanceRoute: FinanceRoute,
  HrRoute: HrRoute,
  InventoryRoute: InventoryRoute,
  ManufacturingRoute: ManufacturingRoute,
  PayrollRoute: PayrollRoute,
  ProcurementRoute: ProcurementRoute,
  ProjectsRoute: ProjectsRoute,
  SalesRoute: SalesRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
